# Generated by Django 4.1.6 on 2023-03-18 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='created',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='review',
            name='rating',
            field=models.IntegerField(default=3),
        ),
    ]
