# Generated by Django 4.1.6 on 2023-02-27 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='leardership',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='review',
            name='participation',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='review',
            name='punctuality',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='review',
            name='respect',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='review',
            name='teamwork',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='staff',
            name='prefix',
            field=models.CharField(choices=[('Prof.', 'Prof.'), ('Dr.', 'Dr.'), ('Mrs.', 'Mrs.'), ('Ms.', 'Mrs.'), ('Mr.', 'Mr.'), ('Mx.', 'Mx.')], default='Mx.', max_length=5),
        ),
        migrations.AddField(
            model_name='student',
            name='leardership',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='participation',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='punctuality',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='respect',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='teamwork',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=100),
        ),
    ]
