# Generated by Django 4.1.6 on 2023-03-09 21:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Karma',
            fields=[
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='base.student')),
            ],
        ),
        migrations.AlterField(
            model_name='endorsement',
            name='leadership',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='endorsement',
            name='participation',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='endorsement',
            name='punctuality',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='endorsement',
            name='respect',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='endorsement',
            name='teamwork',
            field=models.BooleanField(default=False),
        ),
    ]
