# Generated by Django 4.1.6 on 2023-03-21 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_rename_created_review_created_at_review_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='EndorsementStats',
            fields=[
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='base.student')),
            ],
        ),
    ]
