# Generated by Django 4.1.6 on 2023-02-27 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_review_leardership_review_participation_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staff',
            old_name='users',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='users',
            new_name='user',
        ),
    ]
