# Generated by Django 4.1.6 on 2023-03-21 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_endstats'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EndStats',
            new_name='EndorsementStats',
        ),
    ]
