# Generated by Django 4.1.6 on 2023-02-28 00:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_rename_users_staff_user_rename_users_student_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stats',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('leadership', models.IntegerField(default=0)),
                ('respect', models.IntegerField(default=0)),
                ('punctuality', models.IntegerField(default=0)),
                ('participation', models.IntegerField(default=0)),
                ('teamwork', models.IntegerField(default=0)),
                ('karma', models.IntegerField(default=0)),
            ],
        ),
        migrations.RenameField(
            model_name='review',
            old_name='leardership',
            new_name='leadership',
        ),
        migrations.RemoveField(
            model_name='student',
            name='leardership',
        ),
        migrations.RemoveField(
            model_name='student',
            name='participation',
        ),
        migrations.RemoveField(
            model_name='student',
            name='punctuality',
        ),
        migrations.RemoveField(
            model_name='student',
            name='respect',
        ),
        migrations.RemoveField(
            model_name='student',
            name='teamwork',
        ),
        migrations.AddField(
            model_name='student',
            name='stats',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.stats'),
        ),
    ]
