# Generated by Django 4.1.6 on 2023-02-28 02:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_stats_rename_leardership_review_leadership_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stats',
            name='karma',
        ),
    ]
