# Generated by Django 4.1.6 on 2023-03-24 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_rank'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rank',
        ),
    ]
