# Generated by Django 4.1.6 on 2023-04-04 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_rename_action_activity_parameter_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='profile_pic',
        ),
    ]
